### ISSUE TITLE
Reduce permissions

### ISSUE THREAD

**Issue by rugk** [flathub/ind.ie.Gnomit#1]
…because this effectively allows a sandbox escape:

> Almost all popular applications on flathub come with filesystem=host, filesystem=home or device=all 
permissions, that is, write permissions to the user home directory (and more), this effectively means that all it takes to "escape the sandbox" is echo download_and_execute_evil >> ~/.bashrc. That's it.

http://flatkill.org/

So it would be great, if it can be used without it.

**Comment by TingPing** [comment]
It could probably work without it but the command becomes very ugly:

`flatpak run --file-forwarding ind.ie.Gnomit @@ /a/path @@`

The network permission also seems unnecessary.

**Comment by rugk** [comment]
> The network permission also seems unnecessary.

Good point, indeed!

> but the command becomes very ugly

Yeah, but this is one value you set in your git config one time. That's it! And it strengthens the sandbox (not to say it fixes a big "loop hole"), so IMHO it is very much worth it.

**Comment by aral** [comment]
Regarding not having the host file system permission: I don’t understand how that could work as the commit message editor is meant to work with any number of repositories on your machine and the commit message file that is passed to it is repository-specific. Having you re-register your editor per repository is not a tenable proposition. Am I missing something?

Regarding network permissions: I don’t see why that’s necessary either. I will test it without and remove it if it isn’t necessary.

**Comment by rugk** [comment]
Could not you just use relative paths? E.g. allow access to `./.git` or where the file is stored? And if you are in a subdir you may be able to just also whitelist `../.git`, `../../.git` and so on?

**Comment by aral** [comment]
Is /a/path some sort of custom glob? I thought it would only grant access to, literally, /a/path

Aral

**Comment by TingPing** [comment]
Its a file path, any file path...

**Comment by sonnyp** [comment]
https://github.com/indie-mirror/gnomit/pull/7

**Comment by aral** [comment]
Closing this as Sonny’s changes have now been merged.
